frontend:
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.25"
    pullPolicy: IfNotPresent

backend:
  replicaCount: 1
  image:
    repository: httpd
    tag: "2.4"
    pullPolicy: IfNotPresent